services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["go", "run", "./cmd/app/main.go"]
  db:
    image: mysql:8.0
    ports:
      - "3306:3306" # MySQL のデフォルトポート
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
